import 'package:flutter/material.dart';

import '../font/fonts_style.dart';

class NR_5G extends StatefulWidget {
  const NR_5G({super.key});

  @override
  State<NR_5G> createState() => _NR_5GState();
}

class _NR_5GState extends State<NR_5G> {
  late Size mq;
  @override
  Widget build(BuildContext context) {
    mq = MediaQuery.of(context).size;
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: double.infinity,
          color: Colors.black87,
          child: Padding(
            padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 15),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Android Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text("Lat                                   :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("Count of Satellite         :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 80),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text("Lon                                 :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("UE Status                      :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    )
                  ],
                ),
                const SizedBox(height: 10),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR Serving Cell Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR Primary Cell Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text("NR PLMN                        :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR TAC                            :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("gNB ID                             :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR Band                          :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR RRC State                 :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 80),
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text("RAT                                    :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR Cell Identity                :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR Cell Id                          :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR Band Type                  :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        Text("NR Conn. Mode               :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR Measurement Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR Cell Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR ARFCN", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR\nSCS(kHz)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR PCI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR DL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR UL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG Cell Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR ARFCN", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR\nSCS(kHz)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR PCI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR DL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR UL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR Beam Measurement', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR SSB Idx", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-RSRP", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-RSRQ", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-SINR", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG Beam Measurement', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR SSB Idx", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-RSRP", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-RSRQ", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR SS-SINR", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR CA State', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("DL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("UL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG CA State', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("DL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("UL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR SRS Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SRS Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR MTPL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR PC adj", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR DL\nPathLoss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG SRS Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR MTPL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR PC adj", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR DL\nPathLoss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR PUCCH Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR PUCCH Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR MTPL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR PC adj", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR DL\nPathLoss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG PUCCH Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR MTPL", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR PC adj", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 20,),
                        Text("NR DL\nPathLoss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR CSI Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR CSI Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR LI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR CQI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR RI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR CRI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG CSI Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR LI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR CQI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR RI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR CRI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR PMI Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR i1,1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR i1,2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR i1,3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 40,),
                        Text("NR i2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR Downlink Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR DL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR MCS(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR MCS(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG DL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR MCS(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR MCS(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR DL Modulation Rate(%)', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG DL Modulation Rate(%)', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 25,),
                        Text("NR 256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR DL Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Num Rx Ant", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR Num Layers", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG DL Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Num Rx Ant", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR Num Layers", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR DL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR BLER(%)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG DL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 25,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR BLER(%)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Row(
                  children: [
                    Text("NR Uplink Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                    Spacer(),
                    Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                    SizedBox(width: 20),
                    Icon(Icons.arrow_drop_down_circle_sharp, size: 30, color: Colors.green),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR DL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR MCS(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR MCS(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG DL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 30,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR MCS(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 100,),
                        Text("NR MCS(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR UL Modulation Rate(%)', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 15,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR BPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG UL Modulation Rate(%)', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 15,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR BPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 10,),
                        Text("NR 256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR UL Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Mode", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG UL Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Tx Mode", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR UL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR ReTx(%)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
                Text('NR SCG UL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
                const SizedBox(height: 10),
                Row(
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        const SizedBox(height: 15,),
                        Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(height: 5,),
                        Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                    const SizedBox(width: 40,),
                    Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      mainAxisAlignment: MainAxisAlignment.start,
                      children: [
                        Text("NR Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                        const SizedBox(width: 50,),
                        Text("NR ReTx(%)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      ],
                    ),
                  ],
                ),
                Divider(color: Colors.grey),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
