import 'package:flutter/material.dart';
import 'package:internship/font/fonts_style.dart';

class Rlf extends StatefulWidget {
  const Rlf({super.key});

  @override
  State<Rlf> createState() => _RlfState();
}

class _RlfState extends State<Rlf> {
  late Size mq;

  @override
  Widget build(BuildContext context) {
    mq = MediaQuery.of(context).size;
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: double.infinity,
          color: Colors.black87,
          padding: const EdgeInsets.symmetric(vertical: 10, horizontal: 15),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Text('Android Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("Lat                                   :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Count of Satellite         :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 80),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("Lon                                 :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("UE Status                      :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  )
                ],
              ),
              const SizedBox(height: 10),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("Serving Cell Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('Primary Cell Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("PLMN                         :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("TAC                            :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("eNB ID                       :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Band                          :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("RRC State                :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 80),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text("RAT                                     :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Cell Identity                       :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Cell Id                                 :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Time Advance                   :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      Text("Upper Layer\nIndication                           :", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                ],
              ),
              const SizedBox(height: 10),
              Divider(color: Colors.grey),
              Text('Antenna Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("TxAnt", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("Rx Ant", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("MIMO", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("SRS Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("Measurement Cell Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('Cell Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("EARFCN", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("PCI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("DL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("UL BW", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('Inst Measurement', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("RSSI", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("RSRP", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("RSRQ", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("SINR", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('CA Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("CA State", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 100,),
                      Text("CA Cause", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('RSSI', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Ant 0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('RSRP', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Ant 0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('RSRQ', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Ant 0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('SINR', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Ant 0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                      Text("Ant 3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 40,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("PUCCH Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUCCH Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("g(i)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("TCP Command", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("DL Pathloss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUCCH Channel Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Report Mode", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("Rank", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("CQI CW0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("CQI CW1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUCCH Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Schema", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("PUSCH Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUSCH Power Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Tx Power", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("g(i)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("TCP Command", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("DL Pathloss", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUSCH Channel Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Report Mode", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("Rank", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("CQI CW0", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                      Text("CQI CW1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PUSCH Transmission Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Schema", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 25,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("Downlink Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('DL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("CW0(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 20,),
                      Text("CW0(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 20,),
                      Text("CW1(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 20,),
                      Text("CW1(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 20,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('DL CW0 Modulation Rate', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('DL CW1 Modulation Rate', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                      Text("256QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 30,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('PDSCH Transmission Rate', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Mode", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 100,),
                      Text("Schema", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('DL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 70,),
                      Text("RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 70,),
                      Text("BLER",style: AppWidget.whiteTextStyle().copyWith(fontSize: 10),),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Row(
                children: [
                  Text("Uplink Info", style: AppWidget.boldTextStyle().copyWith(fontSize: 20, fontWeight: FontWeight.bold)),
                  Spacer(),
                  Icon(Icons.wifi_tethering, size: 30, color: Colors.green),
                  SizedBox(width: 20),
                  Icon(Icons.play_circle, size: 30, color: Colors.green),
                ],
              ),
              Divider(color: Colors.grey),
              Text('UL MCS', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("MCS(Mode)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 100,),
                      Text("MCS(Avg)", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('UL Modulation Rate', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 40,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("BPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 35,),
                      Text("QPSK", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 35,),
                      Text("16QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 35,),
                      Text("64QAM", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 35,),
                    ],
                  ),
                ],
              ),
              Divider(color: Colors.grey),
              Text('UL Info', style: AppWidget.boldTextStyle().copyWith(color: Colors.orangeAccent, fontSize: 15, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              Row(
                mainAxisAlignment: MainAxisAlignment.start,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const SizedBox(height: 15,),
                      Text("PCell", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell1", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell2", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell3", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(height: 5,),
                      Text("SCell4", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                    ],
                  ),
                  const SizedBox(width: 25,),
                  Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    mainAxisAlignment: MainAxisAlignment.start,
                    children: [
                      Text("Modulation", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 63,),
                      Text("RB", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 63,),
                      Text("BLER", style: AppWidget.whiteTextStyle().copyWith(fontSize: 10)),
                      const SizedBox(width: 63,),
                    ],
                  ),
                ],
              ),
              const SizedBox(height: 50),
            ],
          ),
        ),
      ),
    );
  }
}
